name: akashi_cafe

services:
  db:
    image: postgres:14.6
    # Use the official PostgreSQL image
    container_name: postgres
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "akashi_cafe"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "team4"

  liquibase:
    image: liquibase/liquibase:4.23
    container_name: liquibase
    volumes:
      - ./migration:/liquibase/changelog
      - ./liquibase.properties:/liquibase/liquibase.properties
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/akashi_cafe
      LIQUIBASE_COMMAND_USERNAME: root
      LIQUIBASE_COMMAND_PASSWORD: team4
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.xml
    depends_on:
      - db
    command: ["update"]
    profiles:
      - init
# volumes:
#   db_data:
