[project]
name = "akashi-cafe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask==2.0.1",
    "werkzeug==2.3.7",
]
